Fix compilation on Linux
This patch fixes the following compilation error on Linux:

    COMPILE   src/object.o
  In file included from /usr/include/readline/readline.h:36:0,
                   from src/huron.c:4:
  /usr/include/readline/rltypedefs.h:64:28: error: unknown type name ‘FILE’
  In file included from src/huron.c:4:0:
  /usr/include/readline/readline.h:419:20: error: unknown type name ‘FILE’
  /usr/include/readline/readline.h:542:1: error: unknown type name ‘FILE’
  /usr/include/readline/readline.h:543:1: error: unknown type name ‘FILE’
  /usr/include/readline/readline.h:565:1: error: unknown type name ‘rl_getc_func_t’
  /usr/include/readline/readline.h:867:3: error: unknown type name ‘FILE’
  /usr/include/readline/readline.h:868:3: error: unknown type name ‘FILE’
  make: *** [src/huron.o] Error 1

I have no idea why <readline/readline.h> header depends on <stdio.h> like this.

Signed-off-by: Pekka Enberg <penberg@kernel.org>